// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package org.example.grpctp.stubs;

public interface GetAllComptesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllComptesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<org.example.grpctp.stubs.Compte> 
      getComptesList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  org.example.grpctp.stubs.Compte getComptes(int index);
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  int getComptesCount();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<? extends org.example.grpctp.stubs.CompteOrBuilder> 
      getComptesOrBuilderList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  org.example.grpctp.stubs.CompteOrBuilder getComptesOrBuilder(
      int index);
}
